// frontend/src/App.jsx
import React, { Fragment } from 'react';
import './App.css';
import Nav from "./components/Nav";
import ShowPasswords from './components/ShowPasswords';

const App = () => {
    return (
        <Fragment>
            <Nav />
            <ShowPasswords></ShowPasswords>
        </Fragment>
    );
}

export default App;

// frontend_vuejs/src/App.vue
<template>
  <Nav/>
  <div class="container">
    <ShowPasswords/>
  </div>
</template>

<script>
import Nav from './components/Nav.vue'
import ShowPasswords from './components/ShowPasswords.vue'

export default {
  name: 'App',
  components: {
    Nav,
    ShowPasswords
  }
}
</script>

<style></style>
